### PR TITLE
Minimal interface: installation items identified during RC testing

### PR DESCRIPTION
**Pull request by wasade**
Adds non-python files that were not being included on install

Adds a test to verify the app can be imported and built from the installed entity 

Adds a missing `__init__.py` file to ensure items from `microsetta_private_api.model.vue` can be imported

### CODE REVIEW

**Comment by wasade** [comment]
Travis is continuing to act up... @antgonza, do you know if there are additional things needed to reactivate travis? It doesn't look like this build is showing up (https://travis-ci.com/github/biocore/microsetta-private-api) but from what I see on project settings in GitHub, everything is green

**Comment by wasade** [comment]
Very weird. Tests are running, but not under the biocore organization:

https://travis-ci.org/github/wasade/microsetta-private-api/builds/673849498

**Comment by wasade** [comment]
Now it seems to be running... @antgonza not sure if you did something :) If yes, thanks!!

**Comment by dhakim87** [comment]
Looks like this mostly adds the yaml files, approved to merge when you're ready.

**Pull request merged**
